#ifndef CONFIG_H
    #define CONFIG_H

#define ENEMY_BULLET_SPEED 0.35
#define ENEMY_SHOT_INTERVAL_MS 1500
#define ENEMY_SHOT_INTERVAL_RANGE 2000

#define PLAYER_ENEMY_MIN_DISTANCE 150
#define ENEMY_LAUNCH_MIN_TIME 2000
#define ENEMY_LAUNCH_MAX_TIME 8000

#define ENEMY_SPEED 0.06

#define PLAYER_DAMAGE_MIN 2
#define PLAYER_DAMAGE_MAX 10
#define PLAYER_FORWARD_SPEED 0.3
#define PLAYER_BACKWARD_SPEED 0.15
#define PLAYER_SIDE_SPEED 0.22

#define PISTOL_DAMAGE_MIN 10
#define PISTOL_DAMAGE_MAX 40
#define RIFLE_DAMAGE_MIN 30
#define RIFLE_DAMAGE_MAX 120
#define MACHINE_DAMAGE_MIN 10
#define MACHINE_DAMAGE_MAX 25

#define PISTOL_BULLET_SPEED 1.0
#define RIFLE_BULLET_SPEED 1.5
#define MACHINE_BULLET_SPEED 2.0

#define PISTOL_RELOAD_TIME 180
#define RIFLE_RELOAD_TIME 400
#define MACHINE_RELOAD_TIME 250

#define MUSIC_VOLUME 1.0
#define SOUND_VOLUME 0.7

    #endif /* CONFIG_H */
